name: Calendar Sync with Base44

on:
  schedule:
    # Run every 3 hours (at 00:00, 03:00, 06:00, 09:00, 12:00, 15:00, 18:00, 21:00 UTC)
    - cron: '0 */3 * * *'
    # Run once daily at 02:00 UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  sync-current-month:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' && github.event.schedule == '0 */3 * * *'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create output directory
      run: mkdir -p output
      
    - name: Install package in editable mode
      run: pip install -e .

    - name: Run calendar sync for current month
      env:
        PYTHONPATH: ${{ github.workspace }}:${{ github.workspace }}/src
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        HUBSPOT_API_KEY: ${{ secrets.HUBSPOT_API_KEY }}
        BASE44_API_KEY: ${{ secrets.BASE44_API_KEY }}
        CAMPUS_DB_CONN: ${{ secrets.CAMPUS_DB_CONN }}
        LMS_DB_CONN: ${{ secrets.LMS_DB_CONN }}
      run: |
        python run.py --faculty-reports --current-month --handlers base44sync

  sync-all-months:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' && github.event.schedule == '0 2 * * *'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create output directory
      run: mkdir -p output
      
    - name: Install package in editable mode
      run: pip install -e .

    - name: Run calendar sync for all months
      env:
        PYTHONPATH: ${{ github.workspace }}:${{ github.workspace }}/src
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        HUBSPOT_API_KEY: ${{ secrets.HUBSPOT_API_KEY }}
        BASE44_API_KEY: ${{ secrets.BASE44_API_KEY }}
        CAMPUS_DB_CONN: ${{ secrets.CAMPUS_DB_CONN }}
        LMS_DB_CONN: ${{ secrets.LMS_DB_CONN }}
      run: |
        python run.py --update-all-months --faculty-reports --handlers base44sync

  sync-manual:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create output directory
      run: mkdir -p output
      
    - name: Install package in editable mode
      run: pip install -e .

    - name: Run calendar sync for all months (manual trigger)
      env:
        PYTHONPATH: ${{ github.workspace }}:${{ github.workspace }}/src
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        HUBSPOT_API_KEY: ${{ secrets.HUBSPOT_API_KEY }}
        BASE44_API_KEY: ${{ secrets.BASE44_API_KEY }}
        CAMPUS_DB_CONN: ${{ secrets.CAMPUS_DB_CONN }}
        LMS_DB_CONN: ${{ secrets.LMS_DB_CONN }}
      run: |
        python run.py --update-all-months --faculty-reports --handlers base44sync
        